apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: dev
spec:
  limits:
    - default:
        memory: "500Mi" # If not specified the Container's memory limit is set to 512Mi, which is the default memory limit for the namespace.
        cpu: "0.5"  # If not specified default limit is 1 vCPU per container 
      defaultRequest:
        memory: "500Mi" # If not specified default it will take from whatever specified in limits.default.memory
        cpu: "0.5" # If not specified default it will take from whatever specified in limits.default.cpu
      type: Container 
