apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: test
spec:
  limits:
    - default:
        memory: "1Gi" # If not specified the Container's memory limit is set to 512Mi, which is the default memory limit for the namespace.
        cpu: "1"  # If not specified default limit is 1 vCPU per container 
      defaultRequest:
        memory: "1Gi" # If not specified default it will take from whatever specified in limits.default.memory
        cpu: "1" # If not specified default it will take from whatever specified in limits.default.cpu
      type: Container 
      
